name: Alpine

# Alpine uses MUSL instead os glibc

on:
  workflow_dispatch:
  push:
  pull_request:



# defaults:
#   run:
#     shell: bash

jobs:
  configure:
    name: Alpine
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false

    container:
      image: amd64/alpine

    steps:
     - name: Install packages
       run: |
         apk update
         apk add git perl python3 


     - name: what are we running?
       run: |
          cat /etc/os-release 

     - name: create non-root user
       run: |
          adduser -D tester
          su tester whoami
          
     - name: try chmod
       run: |
          echo abcd >fred.txt
          stat fred.txt
          cat fred.txt
          
          chmod 222 fred.txt
          stat fred.txt

          echo def >joe.txt
          stat joe.txt
          cat joe.txt
          
          chmod u-r,u+w joe.txt
          stat joe.txt 
          cat joe.txt

     - name: try python for chmod
       run: |
          echo abcd >xxx.txt
          stat xxx.txt
          python3 <<__SCRIPT__

          import os
          import stat

          mode = 0
          # mode |= stat.S_IEXEC 
          mode |= stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH
          # mode |= stat.S_IREAD  
          os.chmod('xxx.txt', mode)
      
          __SCRIPT__

          stat xxx.txt
          cat xxx.txt
          
