name: Alpine

# Alpine uses MUSL instead os glibc

on:
  workflow_dispatch:
  push:
  pull_request:



# defaults:
#   run:
#     shell: bash

jobs:
  configure:
    name: Alpine
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false

    container:
      image: amd64/alpine

    steps:
     - name: Install packages
       run: |
         apk update
         apk add git perl python3 


     - name: what are we running?
       run: |
          cat /etc/alpine-release 
          cat /etc/os-release 
          uname -a
          
     - name: try chmod
       run: |
          touch fred.txt
          stat fred.txt
          
          chmod 200 fred.txt
          stat fred.txt

          touch joe.txt
          stat joe.txt
          
          chmod u-r,u+w joe.txt
          stat joe.txt          

     - name: try python for chmod
       run: |
          touch xxx.txt
          stat xxx.txt
          python3 <<__SCRIPT__

          import os

          mode = 0
          # mode |= stat.S_IEXEC 
          mode |= stat.S_IWRITE 
          # mode |= stat.S_IREAD  
          os.chmod('xxx.txt', mode)
      
          __SCRIPT__
          
     - name: stat
       run: |          
          stat xxx.txt
          
