name: Alpine

# Alpine uses MUSL instead os glibc

on:
  workflow_dispatch:
  push:
  pull_request:



# defaults:
#   run:
#     shell: bash

jobs:
  configure:
    name: Alpine
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false

    container:
      image: amd64/alpine

    steps:
     - name: Install packages
       run: |
         apk update
         apk add git perl python3 sudo


     - name: what are we running?
       run: |
          cat /etc/os-release 

     - name: create non-root user
       run: |
          id
          echo $HOME
          echo $SHELL
          echo $PATH
          # add new user
          USER=tester
          adduser -D $USER \
            && mkdir -p /etc/sudoers.d \
            && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
            && chmod 0440 /etc/sudoers.d/$USER 
          echo 'export PATH=/tmp:$PATH' >>/home/tester/.bashrc
          chown tester /home/tester/.bashrc
          echo 'export PATH=/tmp:$PATH' >>/home/tester/.bash_profile
          chown tester /home/tester/.bash_profile          
          ls -al /home/tester
         
     - name: ash_profile
       run: |
          cat /home/tester/.bashrc
          ls -l /home/tester/.bashrc
          cat /etc/passwd
          

     - name: nake cwd world readable
       run: |
          sudo -u tester --login ls -al /home/tester
          chmod 777 .
          
     - name: run as non-root user 
       run: |
          sudo -u tester --login <<END
            echo HOME=$HOME
            echo PWD=$PWD
            cat $HOME/.bashrc
            echo $PATH
            id
            ls -l 
          END

          
            
     - name: try chmod
       run: |
          chmod 777 .
          sudo -u tester --login <<END
          
          echo abcd >fred.txt
          stat fred.txt
          cat fred.txt
          
          chmod 222 fred.txt
          tat fred.txt

          echo def >joe.txt
          stat joe.txt
          cat joe.txt
          
          chmod u-r,u+w joe.txt
          stat joe.txt 
          cat joe.txt
          END

     - name: try python for chmod
       run: |

          sudo -u tester --login <<END
          
          echo abcd >xxx.txt
          stat xxx.txt
          python3 <<__SCRIPT__

          import os
          import stat

          mode = 0
          # mode |= stat.S_IEXEC 
          mode |= stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH
          # mode |= stat.S_IREAD  
          os.chmod('xxx.txt', mode)
      
          __SCRIPT__

          stat xxx.txt
          cat xxx.txt
          END
          
